apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello-world
spec:
  selector:
    matchLabels:
      app: nodejs-hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-hello-world
      annotations:
        # This annotation enables the OpenTelemetry Operator to inject Node.js auto-instrumentation
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: app
        image: demo-nodejs-app:latest
        imagePullPolicy: Never  # Use local image loaded into Kind
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-world-service
spec:
  selector:
    app: nodejs-hello-world
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8080
      nodePort: 30000
  type: NodePort # Use NodePort or LoadBalancer depending on your cluster
